# Generated by Django 4.2.7 on 2023-11-28 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_name', models.CharField(max_length=50, verbose_name='Autor name')),
                ('autor_description', models.TextField(blank=True, null=True, verbose_name='Autor description')),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, verbose_name='genre')),
                ('genre_description', models.TextField(blank=True, null=True, verbose_name='genre description')),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_house_name', models.CharField(max_length=50, verbose_name='Publishing house name')),
                ('publishing_house_description', models.TextField(blank=True, null=True, verbose_name='Publishing house description')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100, verbose_name='Series')),
                ('series_description', models.TextField(blank=True, null=True, verbose_name="Count book's series")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, verbose_name='Book name')),
                ('book_price', models.DecimalField(decimal_places=2, default=0.01, max_digits=6)),
                ('year_publishing', models.DateField(max_length=50, verbose_name='Year publishing book')),
                ('page', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('binding', models.CharField(choices=[('Solid', 'solid'), ('Soft', 'soft'), ('Absent', 'absent')], max_length=6, verbose_name='Binding book')),
                ('format_book', models.CharField(choices=[('84x108/64', '84x108/64'), ('75x90/32', '75x90/32'), ('60x90/16', '60x90/16'), ('70x108/16', '70x108/16'), ('60x90/8', '60x90/8'), ('84x108/8', '84x108/8')], max_length=12, verbose_name='Book format')),
                ('ISBN', models.CharField(max_length=25, verbose_name='ISBN')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Book weight(gramme)')),
                ('age_restrictions', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Age restrictions')),
                ('counter_book', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Count of books available')),
                ('active', models.CharField(choices=[('Y', 'active'), ('N', 'inactive')], max_length=4, verbose_name='Book active')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.autor', verbose_name='autor')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genre', verbose_name='genre')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.publishinghouse', verbose_name='Publishing house')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.series', verbose_name='series')),
            ],
        ),
    ]
